# Generated by Django 4.0.1 on 2022-01-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='violencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Departamento', models.CharField(max_length=100)),
                ('Municipio', models.CharField(max_length=100)),
                ('CodigoDane', models.CharField(max_length=100)),
                ('ArmasMedios', models.CharField(max_length=100)),
                ('FechaHecho', models.DateField()),
                ('Genero', models.CharField(choices=[('MA', 'Masculino'), ('FE', 'Femenino')], default='MA', max_length=2)),
                ('GrupoEtario', models.CharField(max_length=100)),
                ('Cantidad', models.IntegerField()),
            ],
        ),
    ]
